### ISSUE TITLE
MacOS Arm64 Support

### ISSUE THREAD

**Issue by Retr0Aa** [frozein/DoonEngine#13]
Hello! I'm new to C, but when I try running this program on Windows 10, it works, but when I try running it on my MacBook Pro with M2 Chip, I get alot of errors that have to do with the architecture and platform.

**Comment by frozein** [comment]
Hey, this is expected, but not very clearly explained. The linear algebra functions used by the engine uses SSE3 intrinsics for vectorization, which are not supported by the arm architecture. You can disable them pretty easily though by going to dependencies/include/QuickMath/quickmath.h and changing QM_USE_SSE to 0 instead of 1.

**Comment by Retr0Aa** [comment]
Hello! Its me again, I get error "cl.exe is not found" on my macos. Is there any way I can fix this and run the project sucessfully?

**Comment by frozein** [comment]
Hey, cl.exe is the Windows C compiler. To build on Mac, run the included makefile (see "Make on Linux" in the readme). Alternatively, if you use CMake, you could use the included CMake build file to generate project files for the editor of your choice. Let me know if there are any issues!
